.\" $Id: bogom.8,v 1.3 2004/12/28 15:00:28 reidrac Exp reidrac $
.\"
.\" bogom, simple sendmail milter to interface bogofilter
.\" Copyright (C) 2004 Juan J. Martinez <jjm*at*usebox*dot*net>
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License Version 2 as
.\" published by the Free Software Foundation.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.Dd December 25, 2004
.Dt BOGOM 8
.Os
.Sh NAME
.Nm bogom
.Nd simple sendmail milter to interface bogofilter
.Sh SYNOPSIS
.Nm
.Op Fl R | Fl D
.Op Fl t
.Op Fl v
.Op Fl u Ar user
.Op Fl p Ar pipe
.Op Fl b Ar bogo_path
.Op Fl x Ar exclude_string
.Sh DESCRIPTION
The
.Nm
plugin can be used with the milter API of
.Xr sendmail 8
to filter mails using
.Xr bogofilter 1
bayesian filter.
.Pp
.Nm
is intended to be used with only one words database for the whole system.
.Pp
The options are as follows:
.Bl -tag -width "-x exclude_string"
.It Fl R
Reject mail classified as spam
.It Fl D
Discard mail classified as spam
.It Fl t
Train bogofilter with the mail classified as spam/ham
.It Fl v
Verbose logging
.It Fl u Ar user
User to run the milter.
Default: bogofilter 
.It Fl p Ar pipe
Path to the pipe to connect sendmail. Default:
.Pa unix:/var/spool/bogofilter/milter.sock
.It Fl b Ar bogo_path
Path to the
.Xr bogofilter 1
binary.
Default:
.Pa /usr/local/bin/bogofilter
.It Fl x Ar exclude_string
If this string is found in the Subject of a message, it will be
automatically accepted and no filtering operation will be done.
.El
.Pp
Default action is to add the
.Em X-Bogosity
header (Yes, No, Unsure) and deliver the mail. This can be changed with
.Cm -R
or
.Cm -D
when
bogofilter classifies the mail as spam.
.Pp
You should set 
.Em bogofilter_dir
to the directory with system database, usually
.Pa /var/spool/bogofilter ,
in bogofilter's configuration, or simply use the words database of the 
unprivileged user running the milter.
.Pp
.Nm
uses a temporal file to store each individual message and forks a new 
process to scan it with bogofilter. This temporal file uses 
.Pa /tmp
directory, it's owned by the user running the milter and has 0600 mode.
.Pp
The option
.Cm -t
registers the mail after classifying it as spam or ham.
This option can be dangerous because the filter may register errors, so
you should read carefully bogofilter's manual regarding this point.
.Sh SENDMAIL SETUP
You must verify you have milter support in your sendmail binary:
.Pp
.D1
# sendmail -d0.1 -bv root | grep MILTER
.D1
 Compiled with: DNSMAP LOG MAP_REGEX MATCHGECOS MILTER MIME7TO8 MIME8TO7
.Pp
Put the milter in your sendmail configuration by adding the following line to
your mc file:
.Pp
.D1
INPUT_MAIL_FILTER(`bogom',\\
.D1 `S=unix:/var/spool/bogofilter/milter.sock, T=S:30s;R:1m')
.Pp
It assumes the default place for the communication socket.
.Pp
Rebuild your cf and install it. Send HUP signal to sendmail and you're done.
.Sh LOGGING
.Nm
sends messages to
.Xr syslogd 8
using
facility
daemon and
levels
err, notice and info.
.Pp
By default only info and, when needed, err levels will be used. With
.Cm -v
option, extra information will be addressed with notice level plus the
log facility provided in bofogilter.
.Sh SEE ALSO
.Xr sendmail 8 ,
.Xr bogofilter 1 ,
.Xr bogoutil 1 ,
.Xr syslog.conf 5 ,
.Xr syslogd 8
.Pp
http://www.usebox.net/jjm/bogom/
.Sh HISTORY
The first version of
.Nm
was written in the end of 2004.
.Sh AUTHORS
Juan J. Martinez
.Aq jjm@usebox.net

